2021-04-09 16:03:41,146 INFO    MainThread:4548 [wandb_setup.py:_flush():69] setting env: {}
2021-04-09 16:03:41,146 INFO    MainThread:4548 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-09 16:03:41,147 INFO    MainThread:4548 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Leo Huang\Desktop\GP-Derivatives-Variational-Inference\experiments\wandb\run-20210409_160341-2ozhv78a\logs\debug.log
2021-04-09 16:03:41,148 INFO    MainThread:4548 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Leo Huang\Desktop\GP-Derivatives-Variational-Inference\experiments\wandb\run-20210409_160341-2ozhv78a\logs\debug-internal.log
2021-04-09 16:03:41,149 INFO    MainThread:4548 [wandb_init.py:init():369] calling init triggers
2021-04-09 16:03:41,158 INFO    MainThread:4548 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-09 16:03:41,158 INFO    MainThread:4548 [wandb_init.py:init():418] starting backend
2021-04-09 16:03:41,159 INFO    MainThread:4548 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-04-09 16:03:41,182 INFO    MainThread:4548 [backend.py:ensure_launched():123] starting backend process...
2021-04-09 16:03:41,505 INFO    MainThread:4548 [backend.py:ensure_launched():128] started backend process with pid: 9464
2021-04-09 16:03:41,507 INFO    MainThread:4548 [wandb_init.py:init():423] backend started and connected
2021-04-09 16:03:41,508 INFO    MainThread:4548 [wandb_init.py:init():463] updated telemetry
2021-04-09 16:03:41,514 INFO    MainThread:4548 [wandb_init.py:init():482] communicating current version
2021-04-09 16:03:46,518 INFO    MainThread:4548 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-09 16:03:47,740 INFO    MainThread:4548 [wandb_init.py:init():520] starting run threads in backend
2021-04-09 16:03:48,119 INFO    MainThread:4548 [wandb_run.py:_console_start():1524] atexit reg
2021-04-09 16:03:48,121 INFO    MainThread:4548 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-04-09 16:03:48,122 INFO    MainThread:4548 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-04-09 16:03:48,122 INFO    MainThread:4548 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-09 16:03:48,122 INFO    MainThread:4548 [wandb_init.py:init():544] run started, returning control to user process
2021-04-09 16:03:48,133 INFO    MainThread:4548 [wandb_config.py:__setitem__():141] config set learning_rate_hypers = 0.01 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002036972B448>>
2021-04-09 16:03:48,134 INFO    MainThread:4548 [wandb_run.py:_config_callback():749] config_cb learning_rate_hypers 0.01 None
2021-04-09 16:03:48,134 INFO    MainThread:4548 [wandb_config.py:__setitem__():141] config set learning_rate_ngd = 0.1 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002036972B448>>
2021-04-09 16:03:48,135 INFO    MainThread:4548 [wandb_run.py:_config_callback():749] config_cb learning_rate_ngd 0.1 None
2021-04-09 16:03:48,135 INFO    MainThread:4548 [wandb_config.py:__setitem__():141] config set lr_sched = step_lr - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002036972B448>>
2021-04-09 16:03:48,136 INFO    MainThread:4548 [wandb_run.py:_config_callback():749] config_cb lr_sched step_lr None
2021-04-09 16:03:48,136 INFO    MainThread:4548 [wandb_config.py:__setitem__():141] config set num_contour_quadrature = 15 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002036972B448>>
2021-04-09 16:03:48,137 INFO    MainThread:4548 [wandb_run.py:_config_callback():749] config_cb num_contour_quadrature 15 None
2021-04-09 16:03:48,173 INFO    MainThread:4548 [wandb_watch.py:watch():39] Watching
2021-04-09 16:04:10,937 INFO    MainThread:4548 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 255
2021-04-09 16:04:10,938 INFO    MainThread:4548 [wandb_run.py:_restore():1466] restore
2021-04-09 16:04:10,940 INFO    MainThread:4548 [wandb_run.py:_restore():1466] restore
2021-04-09 16:04:14,704 ERROR   MainThread:4548 [wandb_run.py:_atexit_cleanup():1512] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\Leo Huang\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_run.py", line 1502, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\Leo Huang\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_run.py", line 1654, in _on_finish
    print("")
OSError: [Errno 22] Invalid argument
