2021-04-09 14:52:18,545 INFO    MainThread:8284 [wandb_setup.py:_flush():69] setting env: {}
2021-04-09 14:52:18,545 INFO    MainThread:8284 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-09 14:52:18,545 INFO    MainThread:8284 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Leo Huang\Desktop\GP-Derivatives-Variational-Inference\experiments\wandb\run-20210409_145218-1444h52x\logs\debug.log
2021-04-09 14:52:18,545 INFO    MainThread:8284 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Leo Huang\Desktop\GP-Derivatives-Variational-Inference\experiments\wandb\run-20210409_145218-1444h52x\logs\debug-internal.log
2021-04-09 14:52:18,546 INFO    MainThread:8284 [wandb_init.py:init():369] calling init triggers
2021-04-09 14:52:18,547 INFO    MainThread:8284 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-09 14:52:18,547 INFO    MainThread:8284 [wandb_init.py:init():418] starting backend
2021-04-09 14:52:18,547 INFO    MainThread:8284 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-04-09 14:52:18,553 INFO    MainThread:8284 [backend.py:ensure_launched():123] starting backend process...
2021-04-09 14:52:18,623 INFO    MainThread:8284 [backend.py:ensure_launched():128] started backend process with pid: 7860
2021-04-09 14:52:18,624 INFO    MainThread:8284 [wandb_init.py:init():423] backend started and connected
2021-04-09 14:52:18,625 INFO    MainThread:8284 [wandb_init.py:init():463] updated telemetry
2021-04-09 14:52:18,625 INFO    MainThread:8284 [wandb_init.py:init():482] communicating current version
2021-04-09 14:52:19,687 INFO    MainThread:8284 [wandb_init.py:init():487] got version response 
2021-04-09 14:52:19,687 INFO    MainThread:8284 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-09 14:52:49,688 INFO    MainThread:8284 [interface.py:_communicate_run():642] couldn't get run from backend
2021-04-09 14:52:49,688 ERROR   MainThread:8284 [wandb_init.py:init():499] backend process timed out
2021-04-09 14:52:49,688 ERROR   MainThread:8284 [wandb_init.py:init():508] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-04-09 14:52:54,735 INFO    MainThread:8284 [wandb_init.py:teardown():187] tearing down wandb.init
